// Kirie Nexus AI - Client Logic
// Powered by Gemini 3 Pro

const el = {
    prompt: document.getElementById('prompt'),
    imageUpload: document.getElementById('image-upload'),
    generateBtn: document.getElementById('generate-btn'),
    loader: document.getElementById('loader'),
    resultArea: document.getElementById('result-area'),
    resultImg: document.getElementById('result-img'),
    downloadBtn: document.getElementById('download-btn'),
    langSelect: document.getElementById('lang-select')
};

let currentImageUrl = null;
let currentLang = 'ja'; // Default to Japanese

const translations = {
    ja: {
        app_title: "KIRIE NEXUS AI",
        app_badge: "POWERED BY GEMINI 3 PRO",
        input_label: "クリエイティブ・プロンプト",
        input_placeholder: "あなたのビジョンを描写してください... (例: ネオンの雨の中のサイバー侍、切り絵スタイル)",
        image_label: "ソース画像 (オプション)",
        style_label: "スタイルモード選択",
        style_ultimate_name: "究極の切り絵",
        style_ultimate_desc: "標準的な高精細切り絵",
        style_neon_name: "ネオン・フラックス",
        style_neon_desc: "発光するサイバーパンク",
        style_chrono_name: "クロノ・シャドウ",
        style_chrono_desc: "映画的シルエットアート",
        style_quantum_name: "クォンタム・ジオラマ",
        style_quantum_desc: "立体的3D深度",
        style_anime_name: "アニメ・ヴィヴィッド",
        style_anime_desc: "日本のアニメスタイル",
        style_oil_name: "オイル・マスターピース",
        style_oil_desc: "古典的厚塗りアート",
        style_watercolor_name: "ウォーターカラー・ドリーム",
        style_watercolor_desc: "柔らかく芸術的",
        style_cyber_name: "サイバー・リアリズム",
        style_cyber_desc: "8Kフォトリアル",
        btn_generate: "生成を開始",
        btn_processing: "処理中...",
        loader_text: "ニューラルデータを処理中",
        result_footer: "GENERATED BY KIRIE NEXUS AI",
        btn_download: "アセットをダウンロード",
        alert_prompt_empty: "クリエイティブなプロンプトを入力してください。",
        alert_error: "システムエラー: "
    },
    en: {
        app_title: "KIRIE NEXUS AI",
        app_badge: "POWERED BY GEMINI 3 PRO",
        input_label: "Creative Prompt",
        input_placeholder: "Describe your vision... (e.g., A cybernetic samurai in a neon rainstorm, paper cut style)",
        image_label: "Source Image (Optional)",
        style_label: "Select Style Mode",
        style_ultimate_name: "Ultimate Kirie",
        style_ultimate_desc: "Standard High-Fidelity Paper Cut",
        style_neon_name: "Neon Flux",
        style_neon_desc: "Bioluminescent Cyberpunk",
        style_chrono_name: "Chrono Shadow",
        style_chrono_desc: "Cinematic Silhouette Art",
        style_quantum_name: "Quantum Diorama",
        style_quantum_desc: "Volumetric 3D Depth",
        style_anime_name: "Anime Vivid",
        style_anime_desc: "Japanese Animation Style",
        style_oil_name: "Oil Masterpiece",
        style_oil_desc: "Classical Impasto Art",
        style_watercolor_name: "Watercolor Dream",
        style_watercolor_desc: "Soft & Artistic",
        style_cyber_name: "Cyber Realism",
        style_cyber_desc: "8K Photorealistic",
        btn_generate: "Initialize Generation",
        btn_processing: "PROCESSING...",
        loader_text: "PROCESSING NEURAL DATA",
        result_footer: "GENERATED BY KIRIE NEXUS AI",
        btn_download: "Download Asset",
        alert_prompt_empty: "Please enter a creative prompt.",
        alert_error: "System Error: "
    },
    ko: {
        app_title: "KIRIE NEXUS AI",
        app_badge: "POWERED BY GEMINI 3 PRO",
        input_label: "크리에이티브 프롬프트",
        input_placeholder: "비전을 설명해주세요... (예: 네온 비 속의 사이버 사무라이, 종이 오리기 스타일)",
        image_label: "소스 이미지 (선택 사항)",
        style_label: "스타일 모드 선택",
        style_ultimate_name: "궁극의 키리에",
        style_ultimate_desc: "표준 고해상도 종이 오리기",
        style_neon_name: "네온 플럭스",
        style_neon_desc: "발광 사이버펑크",
        style_chrono_name: "크로노 섀도우",
        style_chrono_desc: "영화적 실루엣 아트",
        style_quantum_name: "퀀텀 디오라마",
        style_quantum_desc: "입체적 3D 깊이",
        style_anime_name: "애니메이션 비비드",
        style_anime_desc: "일본 애니메이션 스타일",
        style_oil_name: "오일 마스터피스",
        style_oil_desc: "고전적 임파스토 아트",
        style_watercolor_name: "수채화 드림",
        style_watercolor_desc: "부드럽고 예술적",
        style_cyber_name: "사이버 리얼리즘",
        style_cyber_desc: "8K 포토리얼리스틱",
        btn_generate: "생성 시작",
        btn_processing: "처리 중...",
        loader_text: "신경 데이터 처리 중",
        result_footer: "GENERATED BY KIRIE NEXUS AI",
        btn_download: "에셋 다운로드",
        alert_prompt_empty: "창의적인 프롬프트를 입력해주세요.",
        alert_error: "시스템 오류: "
    },
    zh: {
        app_title: "KIRIE NEXUS AI",
        app_badge: "POWERED BY GEMINI 3 PRO",
        input_label: "创意提示词",
        input_placeholder: "描述您的愿景... (例如：霓虹雨中的赛博武士，剪纸风格)",
        image_label: "源图像 (可选)",
        style_label: "选择风格模式",
        style_ultimate_name: "终极剪纸",
        style_ultimate_desc: "标准高保真剪纸",
        style_neon_name: "霓虹流光",
        style_neon_desc: "发光赛博朋克",
        style_chrono_name: "时空光影",
        style_chrono_desc: "电影级剪影艺术",
        style_quantum_name: "量子立体",
        style_quantum_desc: "体积3D深度",
        style_anime_name: "鲜艳动漫",
        style_anime_desc: "日式动画风格",
        style_oil_name: "油画杰作",
        style_oil_desc: "古典厚涂艺术",
        style_watercolor_name: "水彩梦境",
        style_watercolor_desc: "柔和艺术风格",
        style_cyber_name: "赛博写实",
        style_cyber_desc: "8K照片级真实感",
        btn_generate: "开始生成",
        btn_processing: "处理中...",
        loader_text: "正在处理神经数据",
        result_footer: "GENERATED BY KIRIE NEXUS AI",
        btn_download: "下载资源",
        alert_prompt_empty: "请输入创意提示词。",
        alert_error: "系统错误: "
    }
};

// Initialize
function init() {
    // Language Selection
    el.langSelect.addEventListener('change', (e) => {
        setLanguage(e.target.value);
    });

    // Set initial language
    setLanguage('ja');

    // Generate Action
    el.generateBtn.addEventListener('click', handleGenerate);

    // Download Action
    el.downloadBtn.addEventListener('click', () => {
        if (currentImageUrl) {
            const link = document.createElement('a');
            link.href = currentImageUrl;
            link.download = `kirie-nexus-${Date.now()}.jpg`;
            link.click();
        }
    });

    // Embed Mode Check
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('embed') === 'true') {
        document.body.classList.add('embed-mode');
    }
}

function setLanguage(lang) {
    currentLang = lang;
    const t = translations[lang];
    
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (t[key]) {
            element.textContent = t[key];
        }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
        const key = element.getAttribute('data-i18n-placeholder');
        if (t[key]) {
            element.placeholder = t[key];
        }
    });
}

async function handleGenerate() {
    const t = translations[currentLang];
    const prompt = el.prompt.value.trim();
    if (!prompt) {
        alert(t.alert_prompt_empty);
        return;
    }

    setLoading(true);
    el.resultArea.style.display = 'none';

    try {
        let imageBase64 = null;
        let mimeType = null;
        if (el.imageUpload.files.length > 0) {
            const file = el.imageUpload.files[0];
            // Resize and compress image to avoid payload limits
            imageBase64 = await resizeAndConvertToBase64(file);
            mimeType = "image/jpeg";
        }

        const response = await fetch('/api/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                prompt: prompt,
                image: imageBase64,
                mimeType: mimeType
            })
        });

        const data = await response.json();

        if (!data.success) {
            throw new Error(data.error || 'Generation failed');
        }

        // Apply Watermark (Client-side)
        const watermarkedUrl = await addWatermark(data.imageUrl);
        
        currentImageUrl = watermarkedUrl;
        el.resultImg.src = watermarkedUrl;
        el.resultImg.onload = () => {
            el.resultImg.style.opacity = '1';
        };
        
        el.resultArea.style.display = 'block';
        el.resultArea.scrollIntoView({ behavior: 'smooth' });

    } catch (error) {
        console.error('Error:', error);
        alert(t.alert_error + error.message);
    } finally {
        setLoading(false);
    }
}

function resizeAndConvertToBase64(file, maxWidth = 1024) {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.src = URL.createObjectURL(file);
        img.onload = () => {
            const canvas = document.createElement('canvas');
            let width = img.width;
            let height = img.height;
            
            if (width > maxWidth || height > maxWidth) {
                if (width > height) {
                    height = Math.round(height * (maxWidth / width));
                    width = maxWidth;
                } else {
                    width = Math.round(width * (maxWidth / height));
                    height = maxWidth;
                }
            }
            
            canvas.width = width;
            canvas.height = height;
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0, width, height);
            
            // Get base64 without prefix for API
            const dataUrl = canvas.toDataURL('image/jpeg', 0.8);
            resolve(dataUrl.split(',')[1]);
            
            URL.revokeObjectURL(img.src);
        };
        img.onerror = reject;
    });
}

function fileToBase64(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => {
            // Remove data:image/jpeg;base64, prefix
            const base64 = reader.result.split(',')[1];
            resolve(base64);
        };
        reader.onerror = error => reject(error);
    });
}

function setLoading(isLoading) {
    const t = translations[currentLang];
    if (isLoading) {
        el.generateBtn.disabled = true;
        el.generateBtn.textContent = t.btn_processing;
        el.loader.style.display = 'block';
    } else {
        el.generateBtn.disabled = false;
        el.generateBtn.textContent = t.btn_generate;
        el.loader.style.display = 'none';
    }
}

// Watermark Logic (Ryuya Signature)
function addWatermark(url) {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = "Anonymous";
        
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0);
            
            // Pro Watermark Style
            const fontSize = Math.floor(img.width * 0.04);
            const margin = Math.floor(img.width * 0.03);
            
            ctx.font = `900 ${fontSize}px "Inter", sans-serif`;
            ctx.textAlign = 'end';
            ctx.textBaseline = 'bottom';
            
            // Glow effect
            ctx.shadowColor = '#FFE135'; // NanoBanana Yellow
            ctx.shadowBlur = 10;
            ctx.shadowOffsetX = 0;
            ctx.shadowOffsetY = 0;
            
            ctx.fillStyle = 'rgba(255, 255, 255, 0.9)';
            ctx.fillText('Made in Ryuya', img.width - margin, img.height - margin);
            
            try {
                resolve(canvas.toDataURL('image/jpeg', 0.95));
            } catch (e) {
                reject(e);
            }
        };
        
        img.onerror = (e) => {
            console.warn('Watermark skipped due to load error');
            resolve(url);
        };
        
        img.src = url;
    });
}

// Start
init();
