// Kirie Nexus AI - Client Logic
// Powered by Gemini 3 Pro

const el = {
    prompt: document.getElementById('prompt'),
    generateBtn: document.getElementById('generate-btn'),
    styleCards: document.querySelectorAll('.style-card'),
    loader: document.getElementById('loader'),
    resultArea: document.getElementById('result-area'),
    resultImg: document.getElementById('result-img'),
    downloadBtn: document.getElementById('download-btn'),
    langSelect: document.getElementById('lang-select')
};

let currentStyle = 'ultimate_kirie';
let currentImageUrl = null;
let currentLang = 'ja'; // Default to Japanese

const translations = {
    ja: {
        app_title: "KIRIE NEXUS AI",
        app_badge: "POWERED BY GEMINI 3 PRO",
        input_label: "クリエイティブ・プロンプト",
        input_placeholder: "あなたのビジョンを描写してください... (例: ネオンの雨の中のサイバー侍、切り絵スタイル)",
        style_label: "スタイルモード選択",
        style_ultimate_name: "究極の切り絵",
        style_ultimate_desc: "標準的な高精細切り絵",
        style_neon_name: "ネオン・フラックス",
        style_neon_desc: "発光するサイバーパンク",
        style_chrono_name: "クロノ・シャドウ",
        style_chrono_desc: "映画的シルエットアート",
        style_quantum_name: "クォンタム・ジオラマ",
        style_quantum_desc: "立体的3D深度",
        btn_generate: "生成を開始",
        btn_processing: "処理中...",
        loader_text: "ニューラルデータを処理中",
        result_footer: "GENERATED BY KIRIE NEXUS AI",
        btn_download: "アセットをダウンロード",
        alert_prompt_empty: "クリエイティブなプロンプトを入力してください。",
        alert_error: "システムエラー: "
    },
    en: {
        app_title: "KIRIE NEXUS AI",
        app_badge: "POWERED BY GEMINI 3 PRO",
        input_label: "Creative Prompt",
        input_placeholder: "Describe your vision... (e.g., A cybernetic samurai in a neon rainstorm, paper cut style)",
        style_label: "Select Style Mode",
        style_ultimate_name: "Ultimate Kirie",
        style_ultimate_desc: "Standard High-Fidelity Paper Cut",
        style_neon_name: "Neon Flux",
        style_neon_desc: "Bioluminescent Cyberpunk",
        style_chrono_name: "Chrono Shadow",
        style_chrono_desc: "Cinematic Silhouette Art",
        style_quantum_name: "Quantum Diorama",
        style_quantum_desc: "Volumetric 3D Depth",
        btn_generate: "Initialize Generation",
        btn_processing: "PROCESSING...",
        loader_text: "PROCESSING NEURAL DATA",
        result_footer: "GENERATED BY KIRIE NEXUS AI",
        btn_download: "Download Asset",
        alert_prompt_empty: "Please enter a creative prompt.",
        alert_error: "System Error: "
    },
    ko: {
        app_title: "KIRIE NEXUS AI",
        app_badge: "POWERED BY GEMINI 3 PRO",
        input_label: "크리에이티브 프롬프트",
        input_placeholder: "비전을 설명해주세요... (예: 네온 비 속의 사이버 사무라이, 종이 오리기 스타일)",
        style_label: "스타일 모드 선택",
        style_ultimate_name: "궁극의 키리에",
        style_ultimate_desc: "표준 고해상도 종이 오리기",
        style_neon_name: "네온 플럭스",
        style_neon_desc: "발광 사이버펑크",
        style_chrono_name: "크로노 섀도우",
        style_chrono_desc: "영화적 실루엣 아트",
        style_quantum_name: "퀀텀 디오라마",
        style_quantum_desc: "입체적 3D 깊이",
        btn_generate: "생성 시작",
        btn_processing: "처리 중...",
        loader_text: "신경 데이터 처리 중",
        result_footer: "GENERATED BY KIRIE NEXUS AI",
        btn_download: "에셋 다운로드",
        alert_prompt_empty: "창의적인 프롬프트를 입력해주세요.",
        alert_error: "시스템 오류: "
    },
    zh: {
        app_title: "KIRIE NEXUS AI",
        app_badge: "POWERED BY GEMINI 3 PRO",
        input_label: "创意提示词",
        input_placeholder: "描述您的愿景... (例如：霓虹雨中的赛博武士，剪纸风格)",
        style_label: "选择风格模式",
        style_ultimate_name: "终极剪纸",
        style_ultimate_desc: "标准高保真剪纸",
        style_neon_name: "霓虹流光",
        style_neon_desc: "发光赛博朋克",
        style_chrono_name: "时空光影",
        style_chrono_desc: "电影级剪影艺术",
        style_quantum_name: "量子立体",
        style_quantum_desc: "体积3D深度",
        btn_generate: "开始生成",
        btn_processing: "处理中...",
        loader_text: "正在处理神经数据",
        result_footer: "GENERATED BY KIRIE NEXUS AI",
        btn_download: "下载资源",
        alert_prompt_empty: "请输入创意提示词。",
        alert_error: "系统错误: "
    }
};

// Initialize
function init() {
    // Language Selection
    el.langSelect.addEventListener('change', (e) => {
        setLanguage(e.target.value);
    });

    // Set initial language
    setLanguage('ja');

    // Style Selection
    el.styleCards.forEach(card => {
        card.addEventListener('click', () => {
            el.styleCards.forEach(c => c.classList.remove('active'));
            card.classList.add('active');
            currentStyle = card.dataset.style;
        });
    });

    // Generate Action
    el.generateBtn.addEventListener('click', handleGenerate);

    // Download Action
    el.downloadBtn.addEventListener('click', () => {
        if (currentImageUrl) {
            const link = document.createElement('a');
            link.href = currentImageUrl;
            link.download = `kirie-nexus-${Date.now()}.jpg`;
            link.click();
        }
    });

    // Embed Mode Check
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('embed') === 'true') {
        document.body.classList.add('embed-mode');
    }
}

function setLanguage(lang) {
    currentLang = lang;
    const t = translations[lang];
    
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (t[key]) {
            element.textContent = t[key];
        }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
        const key = element.getAttribute('data-i18n-placeholder');
        if (t[key]) {
            element.placeholder = t[key];
        }
    });
}

async function handleGenerate() {
    const t = translations[currentLang];
    const prompt = el.prompt.value.trim();
    if (!prompt) {
        alert(t.alert_prompt_empty);
        return;
    }

    setLoading(true);
    el.resultArea.style.display = 'none';

    try {
        const response = await fetch('/api/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                prompt: prompt,
                style: currentStyle
            })
        });

        const data = await response.json();

        if (!data.success) {
            throw new Error(data.error || 'Generation failed');
        }

        // Apply Watermark (Client-side)
        const watermarkedUrl = await addWatermark(data.imageUrl);
        
        currentImageUrl = watermarkedUrl;
        el.resultImg.src = watermarkedUrl;
        el.resultImg.onload = () => {
            el.resultImg.style.opacity = '1';
        };
        
        el.resultArea.style.display = 'block';
        el.resultArea.scrollIntoView({ behavior: 'smooth' });

    } catch (error) {
        console.error('Error:', error);
        alert(t.alert_error + error.message);
    } finally {
        setLoading(false);
    }
}

function setLoading(isLoading) {
    const t = translations[currentLang];
    if (isLoading) {
        el.generateBtn.disabled = true;
        el.generateBtn.textContent = t.btn_processing;
        el.loader.style.display = 'block';
    } else {
        el.generateBtn.disabled = false;
        el.generateBtn.textContent = t.btn_generate;
        el.loader.style.display = 'none';
    }
}

// Watermark Logic (Ryuya Signature)
function addWatermark(url) {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = "Anonymous";
        
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0);
            
            // Pro Watermark Style
            const fontSize = Math.floor(img.width * 0.04);
            const margin = Math.floor(img.width * 0.03);
            
            ctx.font = `900 ${fontSize}px "Inter", sans-serif`;
            ctx.textAlign = 'end';
            ctx.textBaseline = 'bottom';
            
            // Glow effect
            ctx.shadowColor = '#FFE135'; // NanoBanana Yellow
            ctx.shadowBlur = 10;
            ctx.shadowOffsetX = 0;
            ctx.shadowOffsetY = 0;
            
            ctx.fillStyle = 'rgba(255, 255, 255, 0.9)';
            ctx.fillText('Ryuya', img.width - margin, img.height - margin);
            
            try {
                resolve(canvas.toDataURL('image/jpeg', 0.95));
            } catch (e) {
                reject(e);
            }
        };
        
        img.onerror = (e) => {
            console.warn('Watermark skipped due to load error');
            resolve(url);
        };
        
        img.src = url;
    });
}

// Start
init();
